import { Metadata } from 'next';
import './global.css';

export const metadata = {
  title: {
    abosolute: '',
    default: 'Next js tutorial',
    template: '%s | peace is learning',
  },
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  );
}
